=== enzo41/School-Registration-Web-App/src/test/datasets.dtd
<!ELEMENT dataset (
    enrollment_sections*,
    enrollments*,
    faculty*,
    sections*,
    student_enrollments*,
    students*,
    subject_prerequisites*,
    subjects*)>

<!ELEMENT enrollment_sections EMPTY>
<!ATTLIST enrollment_sections
    pk CDATA #REQUIRED
    fk_enrollment CDATA #IMPLIED
    fk_sections CDATA #IMPLIED
>

<!ELEMENT enrollments EMPTY>
<!ATTLIST enrollments
    pk CDATA #REQUIRED
    enrollment_number CDATA #IMPLIED
    fk_students CDATA #IMPLIED
    term CDATA #IMPLIED
>

<!ELEMENT faculty EMPTY>
<!ATTLIST faculty
    pk CDATA #REQUIRED
    faculty_number CDATA #IMPLIED
>

<!ELEMENT sections EMPTY>
<!ATTLIST sections
    pk CDATA #REQUIRED
    section_number CDATA #IMPLIED
    fk_subject CDATA #IMPLIED
    fk_faculty CDATA #IMPLIED
    schedule CDATA #IMPLIED
>

<!ELEMENT student_enrollments EMPTY>
<!ATTLIST student_enrollments
    pk CDATA #REQUIRED
    fk_student CDATA #IMPLIED
    fk_enrollment CDATA #IMPLIED
>

<!ELEMENT students EMPTY>
<!ATTLIST students
    pk CDATA #REQUIRED
    student_number CDATA #IMPLIED
    academic_year CDATA #IMPLIED
    scholarship_status CDATA #IMPLIED
>

<!ELEMENT subject_prerequisites EMPTY>
<!ATTLIST subject_prerequisites
    pk CDATA #REQUIRED
    fk_subject CDATA #IMPLIED
    fk_prerequisite CDATA #IMPLIED
>

<!ELEMENT subjects EMPTY>
<!ATTLIST subjects
    pk CDATA #REQUIRED
    subject_id CDATA #IMPLIED
    subject_type CDATA #IMPLIED
    
>

=== enzo41/School-Registration-Web-App/src/test/SectionDaoTest.xml
<!DOCTYPE dataset SYSTEM "src/test/datasets.dtd">
<dataset>
    <faculty pk="0"  faculty_number="0"/>
    <faculty pk="1"  faculty_number="10"/>
    <faculty pk="2"  faculty_number="20"/>
    <faculty pk="3"  faculty_number="30"/>
    <faculty pk="4"  faculty_number="40"/>
    <faculty pk="5"  faculty_number="50"/>

	<subjects pk="1"  subject_id="MATH11"  subject_type="UNDERGRADUATE"/>
	<subjects pk="2"  subject_id="MATH14"  subject_type="UNDERGRADUATE"/>
	<subjects pk="3"  subject_id="MATH53"  subject_type="GRADUATE"/>
	<subjects pk="4"  subject_id="CHEM11"  subject_type="UNDERGRADUATE"/>
	<subjects pk="5"  subject_id="CS11"  subject_type="UNDERGRADUATE"/>
	<subjects pk="6"  subject_id="COM1"  subject_type="UNDERGRADUATE"/>
	<subjects pk="7"  subject_id="PHILO1"  subject_type="GRADUATE"/>
	<subjects pk="8"  subject_id="MA1"  subject_type="UNDERGRADUATE"/>
	<subjects pk="9"  subject_id="MA2"  subject_type="UNDERGRADUATE"/>
	<subjects pk="10"  subject_id="MA3"  subject_type="GRADUATE"/>
	<subjects pk="11"  subject_id="EN1"  subject_type="UNDERGRADUATE"/>
	<subjects pk="12"  subject_id="EN2"  subject_type="GRADUATE"/>
	<subjects pk="13"  subject_id="HI1"  subject_type="UNDERGRADUATE"/>
	<subjects pk="14"  subject_id="HI2"  subject_type="GRADUATE"/>
	
	
	<subject_prerequisites pk="1" fk_subject="3" fk_prerequisite="1"/>
	<subject_prerequisites pk="2" fk_subject="3" fk_prerequisite="2"/>
	<subject_prerequisites pk="3" fk_subject="10" fk_prerequisite="8"/>
	<subject_prerequisites pk="4" fk_subject="10" fk_prerequisite="9"/>
	<subject_prerequisites pk="5" fk_subject="12" fk_prerequisite="11"/>
	
	
    <sections pk="1"  section_number="AAA111"  fk_subject="3"   fk_faculty="0"   schedule="MTH AM10"/>
    <sections pk="2"  section_number="BBB222"  fk_subject="6"   fk_faculty="0"   schedule="TBA"/>
    <sections pk="3"  section_number="CCC333"  fk_subject="5"   fk_faculty="0"   schedule="TBA"/>
    <sections pk="4"  section_number="DDD444"  fk_subject="7"   fk_faculty="0"   schedule="TF PM4"/>
    <sections pk="5"  section_number="EEE555"  fk_subject="5"   fk_faculty="0"   schedule="TBA"/>
    <sections pk="6"  section_number="GGG777"  fk_subject="1"   fk_faculty="0"   schedule="TBA"/>
    <sections pk="7"  section_number="ZZZ000"  fk_subject="4"   fk_faculty="0"   schedule="TF PM4"/>
	<sections pk="8"  section_number="MA110MTAM"  fk_subject="8"   fk_faculty="1"   schedule="MTH AM10"/>
	<sections pk="9"  section_number="MA220TFPM"  fk_subject="9"   fk_faculty="2"   schedule="TF PM4"/>
	<sections pk="10"  section_number="MA330WSAM"  fk_subject="10"   fk_faculty="3"   schedule="WS AM1130"/>
	<sections pk="11"  section_number="EN1040MTAM"  fk_subject="11"   fk_faculty="4"   schedule="MTH AM10"/>
	<sections pk="12"  section_number="EN2050TFPM"  fk_subject="12"   fk_faculty="5"   schedule="TF PM1"/>
	<sections pk="13"  section_number="HI1100WSAM"  fk_subject="13"   fk_faculty="1"   schedule="WS AM1130"/>
	<sections pk="14"  section_number="HI2100TFPM"  fk_subject="14"   fk_faculty="1"   schedule="TF PM1"/>

</dataset>

=== enzo41/School-Registration-Web-App/src/test/SubjectDaoTest.xml
<!DOCTYPE dataset SYSTEM "src/test/datasets.dtd">
<dataset>

	<subjects pk="1"  subject_id="MATH11"  subject_type="UNDERGRADUATE"/>
	<subjects pk="2"  subject_id="MATH14"  subject_type="UNDERGRADUATE"/>
	<subjects pk="3"  subject_id="MATH53"  subject_type="GRADUATE"/>
	<subjects pk="4"  subject_id="CHEM11"  subject_type="UNDERGRADUATE"/>
	<subjects pk="5"  subject_id="CS11"  subject_type="UNDERGRADUATE"/>
	<subjects pk="6"  subject_id="COM1"  subject_type="UNDERGRADUATE"/>
	<subjects pk="7"  subject_id="PHILO1"  subject_type="GRADUATE"/>
	<subjects pk="8"  subject_id="MA1"  subject_type="UNDERGRADUATE"/>
	<subjects pk="9"  subject_id="MA2"  subject_type="UNDERGRADUATE"/>
	<subjects pk="10"  subject_id="MA3"  subject_type="GRADUATE"/>
	<subjects pk="11"  subject_id="EN1"  subject_type="UNDERGRADUATE"/>
	<subjects pk="12"  subject_id="EN2"  subject_type="GRADUATE"/>
	<subjects pk="13"  subject_id="HI1"  subject_type="UNDERGRADUATE"/>
	<subjects pk="14"  subject_id="HI2"  subject_type="GRADUATE"/>

</dataset>

=== enzo41/School-Registration-Web-App/src/test/EnrollmentSectionDaoTest.xml
<!DOCTYPE dataset SYSTEM "src/test/datasets.dtd">
<dataset>

	<students pk="1"	student_number="11"	academic_year="1"	scholarship_status="HALF"/>
	<students pk="2"	student_number="22"	academic_year="2"	scholarship_status="NONE"/>
	<students pk="3"	student_number="33"	academic_year="3"	scholarship_status="HALF"/>
	<students pk="4"	student_number="44"	academic_year="4"	scholarship_status="FULL"/>
	<students pk="5"	student_number="55"	academic_year="1"	scholarship_status="NONE"/>
	
	<enrollments pk="1"	enrollment_number="101"	fk_students="1"	term="Y2014_1ST"/>
	
	<enrollment_sections pk="1"	fk_enrollment="1"	fk_sections="8"/>
	<enrollment_sections pk="2"	fk_enrollment="1"	fk_sections="9"/>
	<enrollment_sections pk="3"	fk_enrollment="1"	fk_sections="10"/>
	<enrollment_sections pk="4"	fk_enrollment="1"	fk_sections="11"/>
	<enrollment_sections pk="5"	fk_enrollment="1"	fk_sections="12"/>
	<enrollment_sections pk="6"	fk_enrollment="1"	fk_sections="13"/>
	<enrollment_sections pk="7"	fk_enrollment="1"	fk_sections="14"/>
	
</dataset>
